[metadata]
name = hhsa_tools
version = 0.1.0
author = TingTW
author_email = dinghsin12345@gmail.com
description = Holo-Hilbert Spectral Analysis with EMD, CEEMDAN, and ICEEMDAN.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/DHCLAIRE/HHSA-Py
license = MIT
license_files = LICENSE, LICENSE.txt
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Information Analysis
keywords = HHSA, Holo-Hilbert, HHT, EMD, CEEMDAN, ICEEMDAN

[options]
packages = find:
python_requires = >=3.10
install_requires =
    numpy>=1.23.0
    scipy>=1.10.0

[options.extras_require]
dev =
    pytest>=7.0.0
plot =
    matplotlib>=3.7.0
    pandas>=2.0.0
neuro =
    mne>=1.0.0
notebook =
    jupyter-notebook>=6.4.0

[options.packages.find]
include =
    hhsa
    hhsa.*
    hhsa_tools
    hhsa_tools.*
